### ISSUE TITLE
Could not find the VTK package due to a missing dependency。

### ISSUE THREAD

**Issue by sicklememe** [ros-noetic-arch/ros-noetic-desktop-full#41]
I don't know why. 
```
-- Found mpi4py: /usr/lib/python3.10/site-packages/mpi4py/include
-- Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY PostgreSQL_INCLUDE_DIR)
-- Could not find the VTK package due to a missing dependency: PostgreSQL
-- Could NOT find Boost: Found unsuitable version "1.80.0", but required is exact version "1.79.0" (found /usr/include, )
-- Could not find the VTK package due to a missing dependency: Boost
CMake Warning at /usr/lib64/cmake/vtk/VTK-vtk-module-find-packages.cmake:603 (find_package):
  By not providing "FindPDAL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PDAL", but
  CMake did not find one.

  Could not find a package configuration file provided by "PDAL" with any of
  the following names:

    PDALConfig.cmake
    pdal-config.cmake

  Add the installation prefix of "PDAL" to CMAKE_PREFIX_PATH or set
  "PDAL_DIR" to a directory containing one of the above files.  If "PDAL"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /usr/lib64/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:25 (find_package)
  CMakeLists.txt:375 (include)


-- Could not find the VTK package due to a missing dependency: PDAL
COMPONENT = openvdb
-- Found OpenVDB: /usr/include (found version "9.1.0") found components: openvdb
-- OpenVDB ABI Version: 9
CMake Error at /usr/lib64/cmake/Boost-1.80.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:

    /usr/lib64/cmake/boost_iostreams-1.80.0/boost_iostreams-config.cmake

  but it set boost_iostreams_FOUND to FALSE so package "boost_iostreams" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_iostreams.so.1.80.0 (release runtime,
  Boost_USE_DEBUG_RUNTIME=TRUE)

  * libboost_iostreams.a (static, Boost_USE_STATIC_LIBS=OFF)

Call Stack (most recent call first):
  /usr/lib64/cmake/Boost-1.80.0/BoostConfig.cmake:262 (boost_find_component)
  /usr/share/cmake/Modules/FindBoost.cmake:594 (find_package)
  /usr/share/cmake/Modules/FindOpenVDB.cmake:499 (find_package)
  /usr/lib64/cmake/vtk/VTK-vtk-module-find-packages.cmake:650 (find_package)
  /usr/lib64/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:25 (find_package)
  CMakeLists.txt:375 (include)


-- Configuring incomplete, errors occurred!
See also "/tmp/makepkg/pcl/src/build/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: pcl
```
/tmp/makepkg/pcl/src/build/CMakeFiles/CMakeOutput.log
```
···
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD succeeded with the following output:
Change Dir: /tmp/makepkg/pcl/src/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/sbin/make -f Makefile cmTC_8c537/fast && /usr/sbin/make  -f CMakeFiles/cmTC_8c537.dir/build.make CMakeFiles/cmTC_8c537.dir/build
make[1]: Entering directory '/tmp/makepkg/pcl/src/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_8c537.dir/src.c.o
/usr/lib/ccache/bin/cc -DCMAKE_HAVE_LIBC_PTHREAD  -march=native -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -fopenmp  -o CMakeFiles/cmTC_8c537.dir/src.c.o -c /tmp/makepkg/pcl/src/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_8c537
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8c537.dir/link.txt --verbose=1
/usr/lib/ccache/bin/cc -march=native -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -fopenmp  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now  CMakeFiles/cmTC_8c537.dir/src.c.o -o cmTC_8c537
make[1]: Leaving directory '/tmp/makepkg/pcl/src/build/CMakeFiles/CMakeTmp'


Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}
```

**Comment by acxz** [comment]
Can you increase the build log output so that we can find out which particular package is failing from the ros dependencies?

**Comment by sicklememe** [comment]
> Can you increase the build log output so that we can find out which particular package is failing from the ros dependencies?

I'm missing some dependencies on my system, `pdal`, `postgresql-libs`, `cli11`.

All the error parts after completing the dependencies are as follows
```
CMake Error at /usr/lib64/cmake/Boost-1.80.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:

    /usr/lib64/cmake/boost_iostreams-1.80.0/boost_iostreams-config.cmake

  but it set boost_iostreams_FOUND to FALSE so package "boost_iostreams" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_iostreams.so.1.80.0 (release runtime,
  Boost_USE_DEBUG_RUNTIME=TRUE)

  * libboost_iostreams.a (static, Boost_USE_STATIC_LIBS=OFF)

Call Stack (most recent call first):
  /usr/lib64/cmake/Boost-1.80.0/BoostConfig.cmake:262 (boost_find_component)
  /usr/share/cmake/Modules/FindBoost.cmake:594 (find_package)
  /usr/share/cmake/Modules/FindOpenVDB.cmake:499 (find_package)
  /usr/lib64/cmake/vtk/VTK-vtk-module-find-packages.cmake:650 (find_package)
  /usr/lib64/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:25 (find_package)
  CMakeLists.txt:375 (include)


-- Configuring incomplete, errors occurred!
See also "/tmp/makepkg/pcl/src/build/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: pcl
```

**Comment by acxz** [comment]
Aha we found our culprit. See the last line in your log.

> `-> error making: pcl`

`pcl` is not a package that the ros-noetic-arch group maintains. For issues regarding the `pcl` package you need to comment over at the pcl AUR package here: https://aur.archlinux.org/packages/pcl

In fact, clicking on the link it looks like someone has already reported the issue: https://aur.archlinux.org/packages/pcl#comment-880849

**Comment by BackMountainDevil** [comment]
@luoiohub .Do you solve this problem?

**Comment by sicklememe** [comment]
> @luoiohub .Do you solve this problem?

After I updated `libharu`, I recompiled the entire package.
I get ideas from this issue
[Build failed. No rule to make target '/usr/lib/libboost_date_time.so.1.78.0'. #39](https://github.com/ros-noetic-arch/ros-noetic-desktop-full/issues/39)
Because updating this package `libharu` alone doesn't change the situation

```
yay -S $(pactree boost -r -l -u | grep 'ros-noetic') --sudoloop --noconfirm --rebuildall
yay -S $(pactree boost -r -l -u | grep 'ros-noetic' -v) --sudoloop --noconfirm --rebuildall
yay -S $(pactree boost-libs -r -l -u | grep 'ros-noetic') --sudoloop --noconfirm --rebuildall
yay -S $(pactree boost-libs -r -l -u | grep 'ros-noetic' -v) --sudoloop --noconfirm --rebuildall
yay -Syu ros-melodic-desktop-full ros-noetic-desktop-full --sudoloop 
```

**Comment by BackMountainDevil** [comment]
ok. A bit difficult for me to solve. give up. Is there another way to run this on Arch? like docker?

**Comment by acxz** [comment]
Did you try running the above commands?

Make sure to not include the `ros-melodic-desktop-full` package in the last line?

If you want to use ROS with docker, take a look at the following project: [rocker](https://github.com/osrf/rocker) or the following docs: http://wiki.ros.org/docker/Tutorials/Docker

I also have a docker image for ros and cudagl, if you use an nvidia gpu to visualize Gazebo. https://hub.docker.com/r/acxz/ros-cudagl

Overall though, I'd recommend just use the packages from the AUR, docker can bring about its own host of issues you may have to work through.

**Comment by BackMountainDevil** [comment]
As you adviced, I try these commands. you say that not include the last line.  So what is next?

```
yay -S $(pactree boost -r -l -u | grep 'ros-noetic') --sudoloop --noconfirm --rebuildall
yay -S $(pactree boost -r -l -u | grep 'ros-noetic' -v) --sudoloop --noconfirm --rebuildall
yay -S $(pactree boost-libs -r -l -u | grep 'ros-noetic') --sudoloop --noconfirm --rebuildall
yay -S $(pactree boost-libs -r -l -u | grep 'ros-noetic' -v) --sudoloop --noconfirm --rebuildall
```

**Comment by AchmadFathoni** [comment]
@BackMountainDevil What is your current error?

**Comment by BackMountainDevil** [comment]
no error occur when excute commands above

From An idea

**Comment by AchmadFathoni** [comment]
> no error occur when excute commands above From An idea
> […](#)
> 在 2022年9月26日，19:51，Achmad Fathoni ***@***.***> 写道： @BackMountainDevil What is your current error? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

Is that mean your issue is solved?

**Comment by BackMountainDevil** [comment]
> > no error occur when excute commands above From An idea
> 
> Is that mean your issue is solved?

I am not sure. no error in tthose four commands. Others commands not found. like `roscore roslaunch rosrun`

**Comment by AchmadFathoni** [comment]
> > > no error occur when excute commands above From An idea
> > 
> > Is that mean your issue is solved?
> 
> I am not sure. no error in tthose four commands. Others commands not found. like `roscore roslaunch rosrun`
> 
> 
Did you run 'source /opt/ros/noetic/setup.bash' first before running those commands?

**Comment by acxz** [comment]
> you say that not include the last line

Do include last line, just dont include the `melodic` package.

For easy copy and paste this is what I meant:
`yay -Syu ros-noetic-desktop-full --sudoloop`

The arguments to `yay` are the packages, since you want to install noetic, you just omit the melodic package.

**Comment by BackMountainDevil** [comment]
> yay -Syu ros-noetic-desktop-full --sudoloop

I try that as you remind. But got error still

```
 yay -Syu ros-noetic-desktop-full --sudoloop
:: Synchronizing package databases...
 endeavouros is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
:: 1 Packages to upgrade.
1  aur/gazebo  11.11.0-2 -> 11.12.0-1
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
==> 1

:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:36]  pcl-1.12.1-2  ros-noetic-pcl-conversions-1.7.4-1  ros-noetic-pcl-ros-1.7.4-1  ros-noetic-perception-pcl-1.7.4-1  ros-noetic-laser-assembler-1.7.8-1  ros-noetic-laser-filters-1.9.0-2  ros-noetic-laser-pipeline-1.6.4-1  ros-noetic-compressed-depth-image-transport-1.14.0-1  ros-noetic-compressed-image-transport-1.14.0-1  ros-noetic-theora-image-transport-1.14.0-1  ros-noetic-image-transport-plugins-1.14.0-1  ros-noetic-image-rotate-1.16.0-1  ros-noetic-image-proc-1.16.0-2  ros-noetic-stereo-image-proc-1.16.0-1  ros-noetic-depth-image-proc-1.16.0-1  ros-noetic-image-view-1.16.0-2  ros-noetic-image-publisher-1.16.0-1  ros-noetic-camera-calibration-1.16.0-1  ros-noetic-image-pipeline-1.16.0-1  ros-noetic-image-common-1.12.0-1  ros-noetic-perception-1.5.0-1  ros-noetic-hardware-interface-0.19.5-1  ros-noetic-controller-interface-0.19.5-1  ros-noetic-realtime-tools-1.16.1-1  ros-noetic-forward-command-controller-0.20.0-1  ros-noetic-position-controllers-0.20.0-1  ros-noetic-controller-manager-msgs-0.19.5-1  ros-noetic-controller-manager-0.19.5-2  ros-noetic-joint-state-controller-0.20.0-1  ros-noetic-diff-drive-controller-0.20.0-1  ros-noetic-control-toolbox-1.19.0-1  ros-noetic-transmission-interface-0.19.5-1  ros-noetic-joint-limits-interface-0.19.5-1  ros-noetic-gazebo-ros-control-2.9.2-4  ros-noetic-urdf-sim-tutorial-0.5.1-1  ros-noetic-desktop-full-1.5.0-1


==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> N
:: PKGBUILD up to date, Skipping (36/0): ros-noetic-compressed-image-transport, ros-noetic-image-rotate, ros-noetic-stereo-image-proc, ros-noetic-image-view, ros-noetic-position-controllers, ros-noetic-joint-limits-interface, ros-noetic-urdf-sim-tutorial, ros-noetic-compressed-depth-image-transport, ros-noetic-theora-image-transport, ros-noetic-realtime-tools, ros-noetic-laser-pipeline, ros-noetic-image-transport-plugins, ros-noetic-image-common, ros-noetic-perception, ros-noetic-hardware-interface, ros-noetic-diff-drive-controller, ros-noetic-transmission-interface, ros-noetic-pcl-conversions, ros-noetic-perception-pcl, ros-noetic-image-pipeline, ros-noetic-controller-interface, ros-noetic-forward-command-controller, ros-noetic-pcl-ros, ros-noetic-laser-assembler, ros-noetic-depth-image-proc, ros-noetic-controller-manager-msgs, ros-noetic-control-toolbox, ros-noetic-gazebo-ros-control, ros-noetic-laser-filters, ros-noetic-image-proc, ros-noetic-image-publisher, ros-noetic-controller-manager, ros-noetic-joint-state-controller, ros-noetic-desktop-full, pcl, ros-noetic-camera-calibration

==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> N

--   Found libusb-1.0, version 1.0.26
-- Found libusb: /usr/lib/libusb-1.0.so  
-- Could NOT find OpenNI (missing: OPENNI_LIBRARIES OPENNI_INCLUDE_DIRS) 
-- OpenNI grabber support: not building because OpenNI not found
-- Found OpenNI2: /usr/lib/libOpenNI2.so;libusb::libusb (found version "2.2.0.33") 
-- OpenNI2 found (version: 2.2.0.33, include: /usr/include/openni2, lib: /usr/lib/libOpenNI2.so;libusb::libusb)
-- Could NOT find Ensenso (missing: ENSENSO_LIBRARIES ENSENSO_INCLUDE_DIRS) 
-- IDS-Imaging Ensenso camera support: not building because Ensenso not found
-- Could NOT find davidSDK (missing: DAVIDSDK_LIBRARY DAVIDSDK_INCLUDE_DIR) 
-- David Vision Systems SDK support: not building because davidSDK not found
-- Could NOT find DSSDK (missing: DSSDK_LIBRARIES DSSDK_INCLUDE_DIRS) 
-- DepthSense SDK support: not building because DSSDK not found
-- Could NOT find RSSDK (missing: RSSDK_LIBRARIES RSSDK_INCLUDE_DIRS) 
-- RealSense SDK support: not building because RSSDK not found
-- Could NOT find RSSDK2
-- RealSense SDK 2.0 (librealsense) support: not building because RSSDK2 not found
-- Checking for module 'metslib'
--   Package 'metslib', required by 'virtual:world', not found
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.12") 
-- Found PNG: /usr/lib/libpng.so (found version "1.6.38") 
-- Found Qhull version 8.0.2
-- Found MPI_C: /usr/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
CMake Warning at /usr/lib64/cmake/vtk/VTK-vtk-module-find-packages.cmake:209 (find_package):
  By not providing "FindCLI11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CLI11", but
  CMake did not find one.

  Could not find a package configuration file provided by "CLI11" with any of
  the following names:

    CLI11Config.cmake
    cli11-config.cmake

  Add the installation prefix of "CLI11" to CMAKE_PREFIX_PATH or set
  "CLI11_DIR" to a directory containing one of the above files.  If "CLI11"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /usr/lib64/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:25 (find_package)
  CMakeLists.txt:375 (include)


-- Could not find the VTK package due to a missing dependency: CLI11
-- Found Embree v3.13.5: /usr/lib/libembree3.so.3.13.5
-- Found Open VKL v1.3.0: /usr/lib/libopenvkl.so.1.3.0
-- Found OSPRay: /usr
-- Found OpenVR: /usr/lib/libopenvr_api.so  
-- Found FontConfig: /usr/lib/libfontconfig.so  
-- Found Python: /usr/bin/python3.10 (found version "3.10.7") found components: Interpreter 
-- Found mpi4py: /usr/lib/python3.10/site-packages/mpi4py/include  
-- Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY PostgreSQL_INCLUDE_DIR) 
-- Could not find the VTK package due to a missing dependency: PostgreSQL
-- Could NOT find Boost: Found unsuitable version "1.80.0", but required is exact version "1.79.0" (found /usr/include, )
-- Could not find the VTK package due to a missing dependency: Boost
CMake Warning at /usr/lib64/cmake/vtk/VTK-vtk-module-find-packages.cmake:603 (find_package):
  By not providing "FindPDAL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PDAL", but
  CMake did not find one.

  Could not find a package configuration file provided by "PDAL" with any of
  the following names:

    PDALConfig.cmake
    pdal-config.cmake

  Add the installation prefix of "PDAL" to CMAKE_PREFIX_PATH or set
  "PDAL_DIR" to a directory containing one of the above files.  If "PDAL"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /usr/lib64/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:25 (find_package)
  CMakeLists.txt:375 (include)


-- Could not find the VTK package due to a missing dependency: PDAL
COMPONENT = openvdb
-- Found OpenVDB: /usr/include (found version "9.1.0") found components: openvdb 
-- OpenVDB ABI Version: 9
CMake Error at /usr/lib64/cmake/Boost-1.80.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:

    /usr/lib64/cmake/boost_iostreams-1.80.0/boost_iostreams-config.cmake

  but it set boost_iostreams_FOUND to FALSE so package "boost_iostreams" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_iostreams.so.1.80.0 (release runtime,
  Boost_USE_DEBUG_RUNTIME=TRUE)

  * libboost_iostreams.a (static, Boost_USE_STATIC_LIBS=OFF)

Call Stack (most recent call first):
  /usr/lib64/cmake/Boost-1.80.0/BoostConfig.cmake:262 (boost_find_component)
  /usr/share/cmake/Modules/FindBoost.cmake:594 (find_package)
  /usr/share/cmake/Modules/FindOpenVDB.cmake:499 (find_package)
  /usr/lib64/cmake/vtk/VTK-vtk-module-find-packages.cmake:650 (find_package)
  /usr/lib64/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:25 (find_package)
  CMakeLists.txt:375 (include)


-- Configuring incomplete, errors occurred!
See also "/home/kearney/.cache/yay/pcl/src/build/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: pcl
```

I think it is time for me to stop diving into this issue. My boss changed the plan.

**Comment by BackMountainDevil** [comment]
> Did you run 'source /opt/ros/noetic/setup.bash' first before running those commands?

Not yet cause I have not idea about that. I try now as you remind

```
$ source /opt/ros/noetic/setup.bash
[kearney@82dm ~]$ rosrun
Usage: rosrun [--prefix cmd] [--debug] PACKAGE EXECUTABLE [ARGS]
  rosrun will locate PACKAGE and try to find
  an executable named EXECUTABLE in the PACKAGE tree.
  If it finds it, it will run it with ARGS.
[kearney@82dm ~]$ roscore
... logging to /home/kearney/.ros/log/bebcbb7c-3e0b-11ed-a00c-28cdc4babb2b/roslaunch-82dm-143665.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://82dm:37691/
ros_comm version 1.15.14


SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.14

NODES

auto-starting new master
process[master]: started with pid [143672]
ROS_MASTER_URI=http://82dm:11311/

setting /run_id to bebcbb7c-3e0b-11ed-a00c-28cdc4babb2b
process[rosout-1]: started with pid [143681]
started core service [/rosout]
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
[kearney@82dm ~]$ roslaunch
Usage: roslaunch [options] [package] <filename> [arg_name:=value...]
       roslaunch [options] <filename> [<filename>...] [arg_name:=value...]

If <filename> is a single dash ('-'), launch XML is read from standard input.

roslaunch: error: you must specify at least one input file
[kearney@82dm ~]$ 
```

**Comment by sicklememe** [comment]
> > yay -Syu ros-noetic-desktop-full --sudoloop
> 
> I try that as you remind. But got error still
> 
> ```
>  yay -Syu ros-noetic-desktop-full --sudoloop
> :: Synchronizing package databases...
>  endeavouros is up to date
>  core is up to date
>  extra is up to date
>  community is up to date
>  multilib is up to date
> :: Starting full system upgrade...
>  there is nothing to do
> :: Searching databases for updates...
> :: Searching AUR for updates...
> :: 1 Packages to upgrade.
> 1  aur/gazebo  11.11.0-2 -> 11.12.0-1
> ==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
> ==> 1
> 
> :: Checking for conflicts...
> :: Checking for inner conflicts...
> [Aur:36]  pcl-1.12.1-2  ros-noetic-pcl-conversions-1.7.4-1  ros-noetic-pcl-ros-1.7.4-1  ros-noetic-perception-pcl-1.7.4-1  ros-noetic-laser-assembler-1.7.8-1  ros-noetic-laser-filters-1.9.0-2  ros-noetic-laser-pipeline-1.6.4-1  ros-noetic-compressed-depth-image-transport-1.14.0-1  ros-noetic-compressed-image-transport-1.14.0-1  ros-noetic-theora-image-transport-1.14.0-1  ros-noetic-image-transport-plugins-1.14.0-1  ros-noetic-image-rotate-1.16.0-1  ros-noetic-image-proc-1.16.0-2  ros-noetic-stereo-image-proc-1.16.0-1  ros-noetic-depth-image-proc-1.16.0-1  ros-noetic-image-view-1.16.0-2  ros-noetic-image-publisher-1.16.0-1  ros-noetic-camera-calibration-1.16.0-1  ros-noetic-image-pipeline-1.16.0-1  ros-noetic-image-common-1.12.0-1  ros-noetic-perception-1.5.0-1  ros-noetic-hardware-interface-0.19.5-1  ros-noetic-controller-interface-0.19.5-1  ros-noetic-realtime-tools-1.16.1-1  ros-noetic-forward-command-controller-0.20.0-1  ros-noetic-position-controllers-0.20.0-1  ros-noetic-controller-manager-msgs-0.19.5-1  ros-noetic-controller-manager-0.19.5-2  ros-noetic-joint-state-controller-0.20.0-1  ros-noetic-diff-drive-controller-0.20.0-1  ros-noetic-control-toolbox-1.19.0-1  ros-noetic-transmission-interface-0.19.5-1  ros-noetic-joint-limits-interface-0.19.5-1  ros-noetic-gazebo-ros-control-2.9.2-4  ros-noetic-urdf-sim-tutorial-0.5.1-1  ros-noetic-desktop-full-1.5.0-1
> 
> 
> ==> Packages to cleanBuild?
> ==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
> ==> N
> :: PKGBUILD up to date, Skipping (36/0): ros-noetic-compressed-image-transport, ros-noetic-image-rotate, ros-noetic-stereo-image-proc, ros-noetic-image-view, ros-noetic-position-controllers, ros-noetic-joint-limits-interface, ros-noetic-urdf-sim-tutorial, ros-noetic-compressed-depth-image-transport, ros-noetic-theora-image-transport, ros-noetic-realtime-tools, ros-noetic-laser-pipeline, ros-noetic-image-transport-plugins, ros-noetic-image-common, ros-noetic-perception, ros-noetic-hardware-interface, ros-noetic-diff-drive-controller, ros-noetic-transmission-interface, ros-noetic-pcl-conversions, ros-noetic-perception-pcl, ros-noetic-image-pipeline, ros-noetic-controller-interface, ros-noetic-forward-command-controller, ros-noetic-pcl-ros, ros-noetic-laser-assembler, ros-noetic-depth-image-proc, ros-noetic-controller-manager-msgs, ros-noetic-control-toolbox, ros-noetic-gazebo-ros-control, ros-noetic-laser-filters, ros-noetic-image-proc, ros-noetic-image-publisher, ros-noetic-controller-manager, ros-noetic-joint-state-controller, ros-noetic-desktop-full, pcl, ros-noetic-camera-calibration
> 
> ==> Diffs to show?
> ==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
> ==> N
> 
> --   Found libusb-1.0, version 1.0.26
> -- Found libusb: /usr/lib/libusb-1.0.so  
> -- Could NOT find OpenNI (missing: OPENNI_LIBRARIES OPENNI_INCLUDE_DIRS) 
> -- OpenNI grabber support: not building because OpenNI not found
> -- Found OpenNI2: /usr/lib/libOpenNI2.so;libusb::libusb (found version "2.2.0.33") 
> -- OpenNI2 found (version: 2.2.0.33, include: /usr/include/openni2, lib: /usr/lib/libOpenNI2.so;libusb::libusb)
> -- Could NOT find Ensenso (missing: ENSENSO_LIBRARIES ENSENSO_INCLUDE_DIRS) 
> -- IDS-Imaging Ensenso camera support: not building because Ensenso not found
> -- Could NOT find davidSDK (missing: DAVIDSDK_LIBRARY DAVIDSDK_INCLUDE_DIR) 
> -- David Vision Systems SDK support: not building because davidSDK not found
> -- Could NOT find DSSDK (missing: DSSDK_LIBRARIES DSSDK_INCLUDE_DIRS) 
> -- DepthSense SDK support: not building because DSSDK not found
> -- Could NOT find RSSDK (missing: RSSDK_LIBRARIES RSSDK_INCLUDE_DIRS) 
> -- RealSense SDK support: not building because RSSDK not found
> -- Could NOT find RSSDK2
> -- RealSense SDK 2.0 (librealsense) support: not building because RSSDK2 not found
> -- Checking for module 'metslib'
> --   Package 'metslib', required by 'virtual:world', not found
> -- Found ZLIB: /usr/lib/libz.so (found version "1.2.12") 
> -- Found PNG: /usr/lib/libpng.so (found version "1.6.38") 
> -- Found Qhull version 8.0.2
> -- Found MPI_C: /usr/lib/libmpi.so (found version "3.1") 
> -- Found MPI_CXX: /usr/lib/libmpi_cxx.so (found version "3.1") 
> -- Found MPI: TRUE (found version "3.1")  
> CMake Warning at /usr/lib64/cmake/vtk/VTK-vtk-module-find-packages.cmake:209 (find_package):
>   By not providing "FindCLI11.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "CLI11", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "CLI11" with any of
>   the following names:
> 
>     CLI11Config.cmake
>     cli11-config.cmake
> 
>   Add the installation prefix of "CLI11" to CMAKE_PREFIX_PATH or set
>   "CLI11_DIR" to a directory containing one of the above files.  If "CLI11"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> Call Stack (most recent call first):
>   /usr/lib64/cmake/vtk/vtk-config.cmake:150 (include)
>   cmake/pcl_find_vtk.cmake:25 (find_package)
>   CMakeLists.txt:375 (include)
> 
> 
> -- Could not find the VTK package due to a missing dependency: CLI11
> -- Found Embree v3.13.5: /usr/lib/libembree3.so.3.13.5
> -- Found Open VKL v1.3.0: /usr/lib/libopenvkl.so.1.3.0
> -- Found OSPRay: /usr
> -- Found OpenVR: /usr/lib/libopenvr_api.so  
> -- Found FontConfig: /usr/lib/libfontconfig.so  
> -- Found Python: /usr/bin/python3.10 (found version "3.10.7") found components: Interpreter 
> -- Found mpi4py: /usr/lib/python3.10/site-packages/mpi4py/include  
> -- Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY PostgreSQL_INCLUDE_DIR) 
> -- Could not find the VTK package due to a missing dependency: PostgreSQL
> -- Could NOT find Boost: Found unsuitable version "1.80.0", but required is exact version "1.79.0" (found /usr/include, )
> -- Could not find the VTK package due to a missing dependency: Boost
> CMake Warning at /usr/lib64/cmake/vtk/VTK-vtk-module-find-packages.cmake:603 (find_package):
>   By not providing "FindPDAL.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "PDAL", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "PDAL" with any of
>   the following names:
> 
>     PDALConfig.cmake
>     pdal-config.cmake
> 
>   Add the installation prefix of "PDAL" to CMAKE_PREFIX_PATH or set
>   "PDAL_DIR" to a directory containing one of the above files.  If "PDAL"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> Call Stack (most recent call first):
>   /usr/lib64/cmake/vtk/vtk-config.cmake:150 (include)
>   cmake/pcl_find_vtk.cmake:25 (find_package)
>   CMakeLists.txt:375 (include)
> 
> 
> -- Could not find the VTK package due to a missing dependency: PDAL
> COMPONENT = openvdb
> -- Found OpenVDB: /usr/include (found version "9.1.0") found components: openvdb 
> -- OpenVDB ABI Version: 9
> CMake Error at /usr/lib64/cmake/Boost-1.80.0/BoostConfig.cmake:141 (find_package):
>   Found package configuration file:
> 
>     /usr/lib64/cmake/boost_iostreams-1.80.0/boost_iostreams-config.cmake
> 
>   but it set boost_iostreams_FOUND to FALSE so package "boost_iostreams" is
>   considered to be NOT FOUND.  Reason given by package:
> 
>   No suitable build variant has been found.
> 
>   The following variants have been tried and rejected:
> 
>   * libboost_iostreams.so.1.80.0 (release runtime,
>   Boost_USE_DEBUG_RUNTIME=TRUE)
> 
>   * libboost_iostreams.a (static, Boost_USE_STATIC_LIBS=OFF)
> 
> Call Stack (most recent call first):
>   /usr/lib64/cmake/Boost-1.80.0/BoostConfig.cmake:262 (boost_find_component)
>   /usr/share/cmake/Modules/FindBoost.cmake:594 (find_package)
>   /usr/share/cmake/Modules/FindOpenVDB.cmake:499 (find_package)
>   /usr/lib64/cmake/vtk/VTK-vtk-module-find-packages.cmake:650 (find_package)
>   /usr/lib64/cmake/vtk/vtk-config.cmake:150 (include)
>   cmake/pcl_find_vtk.cmake:25 (find_package)
>   CMakeLists.txt:375 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/kearney/.cache/yay/pcl/src/build/CMakeFiles/CMakeOutput.log".
> ==> ERROR: A failure occurred in build().
>     Aborting...
>  -> error making: pcl
> ```
> 
> I think it is time for me to stop diving into this issue. My boss changed the plan.

Try installing these packages,`cli11`、`pdal`、`postgresql-libs`、`openvdb`。
I had a similar situation with the installation,Notice the yellow character in error.
The libharu package does not seem to need to be degraded when the PCL package is installed

**Comment by sicklememe** [comment]
> As you adviced, I try these commands. you say that not include the last line. So what is next?
> 
> ```
> yay -S $(pactree boost -r -l -u | grep 'ros-noetic') --sudoloop --noconfirm --rebuildall
> yay -S $(pactree boost -r -l -u | grep 'ros-noetic' -v) --sudoloop --noconfirm --rebuildall
> yay -S $(pactree boost-libs -r -l -u | grep 'ros-noetic') --sudoloop --noconfirm --rebuildall
> yay -S $(pactree boost-libs -r -l -u | grep 'ros-noetic' -v) --sudoloop --noconfirm --rebuildall
> ```

Sorry, I didn't notice when I copied it.
The last line should be: `yay -Syu ros-noetic-desktop-full --sudoloop`

**Comment by BackMountainDevil** [comment]
> Sorry, I didn't notice when I copied it. The last line should be: `yay -Syu ros-noetic-desktop-full --sudoloop`

Never mind. acze shows the correct last line. It is very nice of you to show the five lines

**Comment by BackMountainDevil** [comment]
> Try installing these packages,`cli11`、`pdal`、`postgresql-libs`、`openvdb`

```bash
yay
yay -S cli11 pdal openvdb postgresql-libs
yay -Syu ros-noetic-desktop-full --sudoloop
```

Error
```bash
-- Could NOT find Boost: Found unsuitable version "1.80.0", but required is exact version "1.79.0" (found /usr/include, )
-- Could not find the VTK package due to a missing dependency: Boost
COMPONENT = openvdb
-- Found OpenVDB: /usr/include (found version "9.1.0") found components: openvdb 
-- OpenVDB ABI Version: 9
CMake Error at /usr/lib64/cmake/Boost-1.80.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:

    /usr/lib64/cmake/boost_iostreams-1.80.0/boost_iostreams-config.cmake

  but it set boost_iostreams_FOUND to FALSE so package "boost_iostreams" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_iostreams.so.1.80.0 (release runtime,
  Boost_USE_DEBUG_RUNTIME=TRUE)

  * libboost_iostreams.a (static, Boost_USE_STATIC_LIBS=OFF)

Call Stack (most recent call first):
  /usr/lib64/cmake/Boost-1.80.0/BoostConfig.cmake:262 (boost_find_component)
  /usr/share/cmake/Modules/FindBoost.cmake:594 (find_package)
  /usr/share/cmake/Modules/FindOpenVDB.cmake:499 (find_package)
  /usr/lib64/cmake/vtk/VTK-vtk-module-find-packages.cmake:650 (find_package)
  /usr/lib64/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:25 (find_package)
  CMakeLists.txt:375 (include)


-- Configuring incomplete, errors occurred!
See also "/home/kearney/.cache/yay/pcl/src/build/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: pcl
```
It seems that I should downgrade boost.

And should I update this pkg?
```
:: 1 Packages to upgrade.
1  aur/gazebo  11.11.0-2 -> 11.12.0-1
```

**Comment by sicklememe** [comment]
> > Try installing these packages,、、、`cli11``pdal``postgresql-libs``openvdb`
> 
> ```shell
> yay
> yay -S cli11 pdal openvdb postgresql-libs
> yay -Syu ros-noetic-desktop-full --sudoloop
> ```
> 
> Error
> 
> ```shell
> -- Could NOT find Boost: Found unsuitable version "1.80.0", but required is exact version "1.79.0" (found /usr/include, )
> -- Could not find the VTK package due to a missing dependency: Boost
> COMPONENT = openvdb
> -- Found OpenVDB: /usr/include (found version "9.1.0") found components: openvdb 
> -- OpenVDB ABI Version: 9
> CMake Error at /usr/lib64/cmake/Boost-1.80.0/BoostConfig.cmake:141 (find_package):
>   Found package configuration file:
> 
>     /usr/lib64/cmake/boost_iostreams-1.80.0/boost_iostreams-config.cmake
> 
>   but it set boost_iostreams_FOUND to FALSE so package "boost_iostreams" is
>   considered to be NOT FOUND.  Reason given by package:
> 
>   No suitable build variant has been found.
> 
>   The following variants have been tried and rejected:
> 
>   * libboost_iostreams.so.1.80.0 (release runtime,
>   Boost_USE_DEBUG_RUNTIME=TRUE)
> 
>   * libboost_iostreams.a (static, Boost_USE_STATIC_LIBS=OFF)
> 
> Call Stack (most recent call first):
>   /usr/lib64/cmake/Boost-1.80.0/BoostConfig.cmake:262 (boost_find_component)
>   /usr/share/cmake/Modules/FindBoost.cmake:594 (find_package)
>   /usr/share/cmake/Modules/FindOpenVDB.cmake:499 (find_package)
>   /usr/lib64/cmake/vtk/VTK-vtk-module-find-packages.cmake:650 (find_package)
>   /usr/lib64/cmake/vtk/vtk-config.cmake:150 (include)
>   cmake/pcl_find_vtk.cmake:25 (find_package)
>   CMakeLists.txt:375 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/kearney/.cache/yay/pcl/src/build/CMakeFiles/CMakeOutput.log".
> ==> ERROR: A failure occurred in build().
>     Aborting...
>  -> error making: pcl
> ```
> 
> It seems that I should downgrade boost.
> 
> And should I update this pkg?
> 
> ```
> :: 1 Packages to upgrade.
> 1  aur/gazebo  11.11.0-2 -> 11.12.0-1
> ```

You need to go to the directory `~/.cache/yay/ pcl`, at line 32 by:PKGBUILD, add a line `-DBoost_NO_BOOST_CMAKE=ON`.
Refer to the issue: https://aur.archlinux.org/packages/pcl#comment-880849

**Comment by BackMountainDevil** [comment]
```
cd ~/.cache/yay/pcl
nano PKGBUILD
makepkg
yay -Syu ros-noetic-desktop-full --sudoloop
```
succeed without any error

**Comment by acxz** [comment]
@luoiohub thanks for pointing us to the solution! Hopefully the issue gets resolved soon, with a rebuild of the official `vtk` package.

**Comment by acxz** [comment]
Closing this as pcl package has been updated
